cabal-version:      3.4
name:               bech32m
version:            0.0.0.0
-- synopsis:
-- description:
homepage:           https://github.com/jonathanknowles/bech32m
license:            BSD-3-Clause
license-file:       LICENSE
author:             Jonathan Knowles
maintainer:         mail@jonathanknowles.net
-- copyright:
category:           Codec
build-type:         Custom
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common extensions
    default-extensions:
      ImportQualifiedPost

common warnings
    ghc-options: -Wall

custom-setup
  setup-depends:
    , base
    , cabal-doctest
    , QuickCheck

library
    import:           warnings
                    , extensions
    exposed-modules:
      Codec.Bech32
      Codec.Bech32.Prefix
      Codec.Bech32.Prefix.Char
      Codec.Bech32.Suffix
      Codec.Bech32.Suffix.Char
      Codec.Bech32.Suffix.Checksum
      Codec.Bech32.Suffix.Payload
      Data.Bit
      Data.BitSeq
      Data.Word5
    other-modules:
      Codec.Bech32.Prefix.Char.Types
      Codec.Bech32.Utilities
    -- other-extensions:
    build-depends:    base
                    , containers
                    , finitary
                    , nonempty-containers
                    , text
                    , vector-sized
    hs-source-dirs:   components/bech32m
    default-language: Haskell2010

test-suite bech32m-test
  import:           warnings
                  , extensions
  type: exitcode-stdio-1.0
  main-is: Main.hs
  other-modules:
      Test.QuickCheck.Classes.Hspec
  hs-source-dirs:
      components/bech32m-test
  ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
  build-depends:
    , base
    , bech32m
    , finitary
    , hspec
    , QuickCheck
    , quickcheck-classes
  default-language: Haskell2010

test-suite bech32m-test-docs
  build-depends:
    , base
    , bech32m
    , doctest
    , QuickCheck
  x-doctest-options: --verbose
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs:
    components/bech32m-test-docs
  ghc-options: -threaded
  default-language: Haskell2010
